### ISSUE TITLE
Pipeline to fetch Arbitrum Governance Data - Off Chain and often Text

### ISSUE THREAD

**Issue by DistributedDoge** [OpenDataforWeb3/DataGrantsforARB#11]
The goal of this issue is to surface **reproducible** and **generalizable** ways of obtaining Governance Data related to arbitrum.  By governance data we mean focus on off-chain sources (check approved bounties for inspiration) such as:

- official social media profiles of delagates + stats
- github profiles of grantees
- text of tally proposals
- snapshot votes
- forum posts

Analysts who apply to Governance oriented bounties are encouraged to package their data-ingestion + data-processing logic into reproducible format that allows to re-apply analysis over fresh data to qualify for this bounty. 

For extra credit, pipelines can be more interesting by enriching the data (e.g. apply NLP techniques over text) or reconciling data from multiple sources.

We are being open-minded as to definition and construction of a pipeline (docker containers, python package, dagster/airflow DAG), as long as it allows end-users analyst to easily and automatically:

- obtain interesting and fresh governance data
- apply some interesting analysis over it
- derive Governance oriented insights

**Comment by poupou-web3** [comment]
This overlap with the issue: https://github.com/OpenDataforWeb3/DataGrantsforARB/issues/16
see my answer there: https://github.com/OpenDataforWeb3/DataGrantsforARB/issues/16#issuecomment-1942575286
I'm fine to support having two distinct issues on chain and one-off-chain
