### ISSUE TITLE
Create Spell for new or missing protocols(DEXes/perps/lending/nft) on Dune. 

### ISSUE THREAD

**Issue by chain-l** [OpenDataforWeb3/DataGrantsforARB#14]
Dune is an open-source platform which can allow dashboard creation for protocols deployed on Arbitrum.
It has two layers namely,
1. App Layer 
2. Data Layer
Any Data Enthusiast can create useful analysis by query, visualization or dashboards on the App Layer. This ability comes from the contribution made at Data Layer by open-source enthusiasts. 

In brief from docs of Dune:- 

"Dune's Data Layer allows you and the Wizards you work with to produce scalable and persistent work by standardizing and normalizing data.
We call this data layer Spellbook.
A good example of the power of working in the Dune Data Layer is OpenSea's standardization and normalization of all NFT trades across all chains and versions.

By transforming their raw data and adding it to the opensea.trades table inside of Spellbook, 2 things can happen:
     1. Every Dune Wizard can easily work with OpenSea's data as it's cleaned and standardized.
     2. The data can be referenced in other Spellbook tables ("Spells") like nft.trades; this makes it even more likely that Wizards will incorporate OpenSea data into their work as the nft.trades table contains data from all marketplaces across all chains.

In this way, a project like yours working in the Spellbook Data Layer can get a lot of leverage not only from whatever data analysis projects and visualizations you commission, but by making it more likely other Wizards will find and use your data, build it into their Dashboards, and generate interest in your project.
Though not necessarily required for your project, getting your data normalized, standardized and possibly inserted into one of our sector level tables like nft.trades is definitely recommended!
Once that is done, people working in the App layer will have a much easier time building good queries, visualizations and dashboards since the hardest data engineering parts are already taken care of."

This task encompasses encouraging contributions on the spellbook repo of Dune. 
For example, currently, there are 25 DEX's spells for the Arbitrum chain & very few perps spells though Arbitrum leads L2 in the DeFi category. 
The raw table and decoded table are the primary ones which are used for spell creation, working with raw table can limit the type of skills required to perform any analysis on this data by delegates or community members of Arbitrum DAO. 
We can keep separate tasks for a spell of protocols that have received any grant from Arbitrum DAO or Foundation. While we encourage these protocols as a priority we shall also allow spell creation for any protocol deployed on Arbitrum One or Nova. This will certainly reward in the long term to transparent data. 

I believe each task can be between $1-2k and we can aim for 25 protocols to be added.

**Comment by ARDev097** [comment]
Hi,
I have added spell for Sterling Finance DEX & SharkySwap DEX about their trades on Arbitrum chain.
The PR can be found here:- [https://github.com/duneanalytics/spellbook/pull/5385](https://github.com/duneanalytics/spellbook/pull/5385)

Let me know if anything I need to do for making it eligible for the task completion.
Also, should I submit on DeWork?
