### ISSUE TITLE
Regenerative Behavior Scoring

### ISSUE THREAD

**Issue by omnianalytics** [OpenDataforWeb3/DataGrantsforARB#20]
**Objective**: We want to offer an easy avenue for gamified participation within the Arbitrum eco-system through a regenerative behavior scoring system that takes into account a wallet address’s on chain footprint. We’d want the score to account for ways the wallet is utilizing and securing the chain as well as how it fosters coordination and encourages inter-community collaboration.

**Data**: Arbitrum Blockchain data pre-processed for easier analysis

**Methodology**: The data scientists will develop a taxonomy of chain and community supportive behaviors that can be tracked through the Arbitrum blockchain. These activities could include, but are not limited to making transfers, bridging funds, holding $ARB, providing liquidity, deploying contracts, donating to public goods, voting on proposals, etc. With these sets of behaviors, code would be developed to codify and track each using observable data on the blockchain. Weights for each behavior could be determined by various crowd sourcing means and then back end infrastructure could be constructed to continually track and score wallets as they move about the 
Arbitrum eco-system.

**Deliverable**: A set of behaviors and corresponding weights that can be used to construct a regenerative behavior score for any wallet that has interacted with the Arbitrum L2 blockchain. A dataset should also be returned with the scores for existing wallets and an analysis of the distribution of scores and comparisons of the existence of the various regenerative behaviors tracked.

**Comment by epowell101** [comment]
Note that this issue is inspired in part by Issue #19

**Comment by poupou-web3** [comment]
To me, this may look like the analysis part of https://github.com/OpenDataforWeb3/DataGrantsforARB/issues/21 and thus I would flag it with #analysis instead of #data
