### ISSUE TITLE
Analysis of Delegates Voting Patterns in Arbitrum Proposals

### ISSUE THREAD

**Issue by poupou-web3** [OpenDataforWeb3/DataGrantsforARB#7]
**Objective**: The project aims to analyze delegate voting patterns in Arbitrum proposals, with a special focus on identifying consistent voting behaviors and correlations. A key aspect is to establish a process that not only serves this analysis but also sets a foundation for future, reusable data collection and analysis efforts.

**Methodology**:

1. **Reusable Data Collection**:
    
    - Develop a data collection system using the Snapshot GraphQL API ([https://docs.snapshot.org/tools/api](https://docs.snapshot.org/tools/api)) designed for reusability. This involves creating a modular, well-documented codebase that can be easily adapted or updated.
    - The system should extract key data elements such as voter identities, vote counts, and voting reasons in a format that is maintainable and scalable.
    - Ensure capability for ongoing data collection to allow analysis of new proposals as they are introduced.
2. **Data Analysis**:
    
    - Conduct a comprehensive analysis of the dataset to identify any consistent voting patterns or correlations among delegates.
    - Utilize robust statistical methods for analyzing voting behaviors, with a focus on repeated voting trends across different proposals.
    - Documentation of the analysis process and methodologies used should be thorough, to facilitate future analyses and replication of the study.

**Approach to Analysis**: The project is open to various analytical methods, with the requirement that the analysis be systematic, well-structured, and findings clearly explained. Innovative analytical techniques are encouraged, especially those that can provide deeper insights into the delegate voting dynamics within the Arbitrum governance framework.

**Comment by katerinabc** [comment]
Snapshot data is available here https://pink-mad-heron-685.mypinata.cloud/ipfs/QmSBUQ8d8DuDs7ZtrouFoFfXsavh2aUt8m5saYmHHcFrBF

Further instructions about how the data was gathered is available here: https://gitlab.com/katerinabc/OpenDataARB

**Comment by ARDev097** [comment]
This report aims to explore the voting patterns across various proposals and voters within the Arbitrum DAO blockchain ecosystem. The analysis delves into understanding trends and patterns within the off-chain voting system, including the distribution of voting power among voters, outlier detection, voter engagement, and proposal-specific insights.

Analysis Report Link (IPFS):- [Report Link](https://green-total-quail-829.mypinata.cloud/ipfs/QmamH54ZmbpHvtLXGoXnngTkY1CMEBFgQdEuxV8ijTucZX)

Github Repo Link:- [Github Link](https://github.com/ARDev097/Voting-Power-Analysis)

**Submitting here as I am not able to submit on DeWork.**
