### ISSUE TITLE
Comprehensive data collection of cross-program funding for Arbitrum grantees

### ISSUE THREAD

**Issue by poupou-web3** [OpenDataforWeb3/DataGrantsforARB#8]
This issue focuses on a detailed examination of funding patterns for projects that have received grants from the Arbitrum Foundation. The primary objective is to identify whether these projects have also secured funding from other notable grant programs in the web3 ecosystem, such as Optimism, Gitcoin, Ethereum, and Giveth. This investigation aims to provide insights into the overlap and distribution of grant funding across different platforms and initiatives.

1. **Data Compilation**: Compile a comprehensive list of all projects that have been granted funding by the Arbitrum Foundation.
2. **Cross-Platform Analysis**: Investigate and document whether these projects have received funding from other ecosystems like (and are not limited to) Optimism, Gitcoin, Ethereum, and Giveth. This should include:
    - Identifying the specific grant program (e.g., GR19).
    - Noting the ecosystem where the grant was awarded (e.g., Gitcoin).
3. **Funding Details Documentation**: For each instance of funding received by a project, record:
    - The amount of funding.
    - The number of voters involved (or 'NA' if not applicable).
    - The total amount received from that particular program.
    - any other metric you find relevant
	- **Grant Submission Archival**: Where possible, provide a link to the original grant submission. Alternatively, archive a text file of the grant submission in a folder named after the project.

Expected Outcomes: The completion of this task will result in a detailed dataset that maps the landscape of grant funding for projects within the Arbitrum ecosystem. This dataset will be instrumental in uncovering trends and patterns in cross-program funding, offering significant insights into the dynamics of grant allocations. A critical aspect of this analysis is its potential to bolster transparency in the funding process. By providing a clear view of the total funding each project receives across different platforms, we can offer valuable information that may influence the selection process for future Arbitrum grantees. This transparent approach to understanding funding amounts received by projects not only aids in decision-making for grant allocations but also promotes fairness and accountability in the wider web3 funding community.

**Comment by epowell101** [comment]
Thanks @poupou-web3 - seems very valuable.  Could this include a fork of or an extension of https://github.com/davidgasquez/gitcoin-grants-data-portal ?

Or is such an extension itself worthy of an issue and then actually using it to deliver the useful analysis is an additional issue and hence bounty?

**Comment by DistributedDoge** [comment]
There is an existing effort to collect information about protocol-level grants for various ecosystems and upload collected information to Dune. 

Proposed schema is very close to what they have, which means submissions for this particular bounty should be quite easy to share with them (and vice versa, data from there can help bounty providers):

https://github.com/andrewhong5297/Crypto-Grants-Analysis/blob/main/uploads/evm_grants.csv

**Comment by epowell101** [comment]
Hey I pinged the creator fwiw - we had already connected as they help lead another data community centered around Dune and I'm due to go on their Twitter space next Wednesday.  Small world and thank you @DistributedDoge for pointing out this project!!

**Comment by jchanolm** [comment]
Hi @epowell101 and @poupou-web3 - 

The path to my grantee research / ingestion notebook changed since my original submission.

Updated path is here: https://github.com/jchanolm/arbitrum-data/tree/main/notebooks/manual-research-ingest

**Comment by spravin3** [comment]
Hi @epowell101  and @poupou-web3 

Resharing my submission from last saturday from dework to here. (_skp_onchain_ on dework/discord)

Detailed document here, showcasing the approach, the findings and recommendations
https://docs.google.com/document/d/1JlcrLWcFSBB9wiNUIP2SaqxVLz36kiQ5IsKrGR3Aqmo/edit?usp=sharing

All the datasets here
https://docs.google.com/spreadsheets/d/1InTtQRkrXY880qVnFvPGQ5kt0OR8zNkIHzTNicXt88M/edit?usp=sharing

(very small files, hence sheets was used)
